export const TRAINING_EXPERIENCE_OPTIONS = [
  '0-6 months',
  '6months -1 year',
  '1-3years',
  '3-5 years',
  '5years+'
];

export const GOALS_OPTIONS = [
  'Less Pain',
  'Move Easier',
  'Get Stronger',
  'Better Balance',
  'More Stamina',
  'Healthy Weight',
  'Better Blood Sugar',
  'Stronger Bones',
  'Better Sleep & Energy',
  'Back to Daily Life'
];

export const SESSIONS_PER_WEEK_OPTIONS = ['1', '2', '3', '4', '5', '6', '7'];

export const CHRONIC_DISEASES_OPTIONS = [
  'Knee osteoarthritis (knee arthritis / wear-and-tear)',
  'Hip osteoarthritis (hip arthritis)',
  'Hand osteoarthritis (hand arthritis)',
  'Rheumatoid arthritis (RA)',
  'Psoriatic arthritis (PsA)',
  'Ankylosing spondylitis / axial spondyloarthritis (AS / axSpA)',
  'Osteoporosis (bone thinning)',
  'Chronic low back pain (chronic back pain)',
  'Chronic neck pain (chronic neck pain)',
  'Degenerative disc disease - lumbar/cervical (DDD)',
  'Lumbar radiculopathy (sciatica)',
  'Spinal stenosis - lumbar/cervical (narrowed spine)',
  'Adult scoliosis (curved spine)',
  'Thoracic hyperkyphosis (hunchback / rounded back)',
  'Shoulder impingement syndrome (swimmer\'s shoulder)',
  'Rotator cuff tendinopathy/tear (rotator cuff injury)',
  'Adhesive capsulitis (frozen shoulder)',
  'Glenohumeral osteoarthritis (shoulder arthritis)',
  'Lateral epicondylalgia (tennis elbow)',
  'Medial epicondylalgia (golfer\'s elbow)',
  'De Quervain tenosynovitis (thumb tendonitis)',
  'Carpal tunnel syndrome (carpal tunnel)',
  'Cubital tunnel syndrome (ulnar nerve entrapment)',
  'Femoroacetabular impingement / hip labral pathology (hip impingement)',
  'Patellofemoral pain syndrome (runner\'s knee)',
  'Patellar tendinopathy (jumper\'s knee)',
  'Achilles tendinopathy (Achilles tendonitis)',
  'Plantar fasciopathy (plantar fasciitis / heel pain)',
  'Iliotibial band syndrome (IT band syndrome)',
  'Greater trochanteric pain syndrome (hip bursitis)',
  'Chronic ankle instability (weak/rolling ankle)',
  'Temporomandibular disorder (TMJ dysfunction / TMD)',
  'Myofascial pain syndrome (trigger points)',
  'Fibromyalgia (fibro)',
  'Hypermobility spectrum disorder / hEDS (joint hypermobility)',
  'Lymphedema (chronic swelling)',
  'Limb loss with prosthetic gait needs (amputation with prosthesis)',
  'Osteitis pubis (pubic bone inflammation)',
  'Chronic shoulder instability (loose shoulder)',
  'Stroke sequelae (post-stroke)',
  'Parkinson disease (Parkinson\'s)',
  'Multiple sclerosis (MS)',
  'Cerebral palsy - adolescent/adult (CP)',
  'Traumatic brain injury sequelae (post-TBI)',
  'Spinal cord injury sequelae (SCI)',
  'Peripheral neuropathy (nerve damage in feet/hands)',
  'Charcot-Marie-Tooth disease (CMT)',
  'Cervical dystonia (spasmodic torticollis)',
  'Post-polio syndrome (late effects of polio)',
  'Vestibular hypofunction - unilateral or bilateral (inner-ear balance loss)',
  'Benign paroxysmal positional vertigo (BPPV / positional vertigo)',
  'Ataxia syndromes (balance/coordination disorder)',
  'Balance impairment and fall risk (falls risk)',
  'Post-concussion syndrome (persistent concussion symptoms)',
  'Coronary artery disease / stable angina (heart disease / chest pain)',
  'Chronic heart failure (CHF / weak heart)',
  'Hypertension (high blood pressure)',
  'Peripheral artery disease with claudication (PAD / poor leg circulation)',
  'Dyslipidemia (high cholesterol)',
  'Type 2 diabetes mellitus (type 2 diabetes)',
  'Type 1 diabetes mellitus (type 1 diabetes)',
  'Prediabetes / metabolic syndrome (pre-diabetes)',
  'Obesity (clinical obesity)',
  'Nonalcoholic fatty liver disease / NASH (fatty liver)',
  'Chronic obstructive pulmonary disease (COPD / chronic bronchitis / emphysema)',
  'Persistent asthma (asthma)',
  'Interstitial lung disease / pulmonary fibrosis (lung scarring)',
  'Cystic fibrosis (CF)',
  'Post-COVID condition (long COVID)',
  'Obstructive sleep apnea (sleep apnea)',
  'Chronic kidney disease - stages 1-4 (CKD)',
  'Cancer survivorship with deconditioning/fatigue (post-cancer fatigue)',
  'Post-mastectomy shoulder dysfunction (post-mastectomy tightness)',
  'Pelvic floor dysfunction (pelvic floor disorder)',
  'Stress urinary incontinence (leak with cough/sneeze)',
  'Urge urinary incontinence / overactive bladder (OAB)',
  'Mixed urinary incontinence (mixed incontinence)',
  'Pelvic organ prolapse (dropped pelvic organs)',
  'Chronic pelvic pain (CPP)',
  'Dyspareunia related to pelvic floor (painful intercourse)',
  'Chronic prostatitis / chronic pelvic pain syndrome (CP/CPPS)',
  'Diastasis recti abdominis (ab separation)',
  'Pregnancy-related lumbopelvic pain (pregnancy back/hip pain)',
  'Primary chronic pain conditions (chronic primary pain)',
  'Complex regional pain syndrome (CRPS / reflex sympathetic dystrophy)',
  'Hemophilia with joint arthropathy (bleeding-disorder joint damage)',
  'Thoracic outlet syndrome (TOS)',
  'Cervicogenic headache (neck-related headache)',
  'Migraine with cervical/vestibular components (migraine)',
  'Chronic venous insufficiency with edema (leg vein insufficiency)'
];

export const INJURIES_OPTIONS = [
  'Lower back pain [Non-specific low back pain]',
  'Lower back pain with shooting leg pain (sciatica) [Lumbar disc herniation with radiculopathy]',
  'Back pain worse when arching backward [Lumbar facet joint pain]',
  'One-sided buttock/back pain near the "dimples" [Sacroiliac joint dysfunction]',
  'Neck pain or stiffness [Cervical strain]',
  'Neck pain after a car accident [Whiplash-associated disorder]',
  'Headache that starts in the neck [Cervicogenic headache]',
  'Shoulder pain when lifting to the side [Rotator cuff tendinopathy]',
  'Sudden shoulder weakness after injury [Rotator cuff tear]',
  'Shoulder pinch when raising arm overhead [Subacromial impingement]',
  'Stiff shoulder that barely moves [Frozen shoulder (adhesive capsulitis)]',
  'Front-of-shoulder pain with lifting [Biceps tendinopathy]',
  'Shoulder feels loose or like it might pop out [Shoulder instability]',
  'Top of shoulder pain after a fall [AC joint sprain]',
  'Deep shoulder click or catch with overhead use [Labral tear (SLAP/Bankart)]',
  'Outer elbow pain with gripping [Tennis elbow (lateral epicondylitis)]',
  'Inner elbow pain with gripping [Golfer\'s elbow (medial epicondylitis)]',
  'Elbow pain from throwing [UCL sprain]',
  'Swollen bump on back of elbow [Olecranon bursitis]',
  'Hand numbness or tingling at night [Carpal tunnel syndrome]',
  'Thumb-side wrist pain with lifting a baby or phone [De Quervain tenosynovitis]',
  'Wrist pain on pinky side after a fall [TFCC injury]',
  'Sore wrist after a fall [Wrist sprain]',
  'Thumb hurts after a fall while holding something [Skier\'s thumb (UCL sprain)]',
  'Mid-back tightness or ache [Thoracic spine pain]',
  'Chest wall pain that is tender to touch [Costochondritis]',
  'Stiff or achy hip when walking [Hip osteoarthritis]',
  'Pinch at the front of the hip with deep squats [Femoroacetabular impingement (FAI)]',
  'Pain on the outside of the hip when lying on that side [Gluteal tendinopathy / GTPS]',
  'Front hip or groin pull [Hip flexor strain]',
  'Buttock pain with sitting, maybe leg tingling [Piriformis syndrome]',
  'Hip clicking or catching when turning [Hip labral tear]',
  'Pulled hamstring [Hamstring strain]',
  'Pulled quad [Quadriceps strain]',
  'Groin strain [Adductor strain]',
  'Kneecap pain with stairs or squats [Patellofemoral pain (runner\'s knee)]',
  'Tender spot just below the kneecap [Patellar tendinopathy (jumper\'s knee)]',
  'Knee clicks, locks, or hurts after a twist [Meniscus tear]',
  'Knee gave way after a twist or landing [ACL tear/sprain]',
  'Inner knee soreness after a side hit [MCL sprain]',
  'Stiff or achy knee with activity [Knee osteoarthritis]',
  'Outside knee pain while running [Iliotibial band syndrome]',
  'Swollen kneecap from lots of kneeling [Prepatellar bursitis]',
  'Shin pain after starting or upping running [Shin splints (medial tibial stress syndrome)]',
  'Pinpoint bone pain that worsens with impact [Stress fracture (tibia or metatarsals)]',
  'Pulled calf [Calf strain]',
  'Achy or sore Achilles tendon [Achilles tendinopathy]',
  'Rolled ankle with swelling on the outside [Lateral ankle sprain]',
  'Pain above the ankle after twisting the leg [High ankle sprain (syndesmotic)]',
  'Heel pain with first steps in the morning [Plantar fasciitis]'
];

export const WEIGHT_GOAL_OPTIONS = ['Lose Weight', 'Gain Weight', 'Maintain Weight'];

export const MONTHLY_BUDGET_OPTIONS = ['0-30zł', '30-60zł', '60-100zł', '100-200zł', '200-500zł', '500zł+'];

export const AVAILABILITY_OPTIONS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export const COOPERATION_OPTIONS = ['On site', 'Remote', 'Hybrid'];

export const GENDER_OPTIONS = ['Male', 'Female', 'Other'];

export const CITIES_OPTIONS = [
  'Warszawa',
  'Kraków',
  'Wrocław',
  'Łódź',
  'Poznań',
  'Gdańsk',
  'Szczecin',
  'Lublin',
  'Bydgoszcz',
  'Białystok',
  'Katowice',
  'Gdynia',
  'Częstochowa',
  'Rzeszów',
  'Radom',
  'Toruń',
  'Sosnowiec',
  'Kielce',
  'Gliwice',
  'Olsztyn',
  'Bielsko-Biała',
  'Zabrze',
  'Bytom',
  'Zielona Góra',
  'Rybnik',
  'Ruda Śląska',
  'Opole',
  'Tychy',
  'Gorzów Wielkopolski',
  'Dąbrowa Górnicza',
  'Elbląg',
  'Płock',
  'Koszalin',
  'Tarnów',
  'Włocławek',
  'Chorzów',
  'Wałbrzych',
  'Kalisz',
  'Legnica',
  'Grudziądz',
  'Jaworzno',
  'Słupsk',
  'Jastrzębie-Zdrój',
  'Nowy Sącz',
  'Jelenia Góra',
  'Siedlce',
  'Mysłowice',
  'Konin',
  'Piła',
  'Piotrków Trybunalski',
  'Inowrocław',
  'Lubin',
  'Ostrów Wielkopolski',
  'Suwałki',
  'Stargard',
  'Gniezno',
  'Ostrowiec Świętokrzyski',
  'Siemianowice Śląskie',
  'Głogów',
  'Pabianice',
  'Leszno',
  'Żory',
  'Zamość',
  'Pruszków',
  'Łomża',
  'Ełk',
  'Tomaszów Mazowiecki',
  'Chełm',
  'Mielec',
  'Kędzierzyn-Koźle',
  'Przemyśl',
  'Stalowa Wola',
  'Tczew',
  'Biała Podlaska',
  'Bełchatów',
  'Świdnica',
  'Będzin',
  'Zgierz',
  'Piekary Śląskie',
  'Legionowo'
];
